<?php
// view/mvit-auction/auction/delete.phtml:

$title = 'Delete auction';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($auction->header); ?>' by
    '<?php echo $this->escapeHtml($auction->price); ?>'?
</p>
<?php
$url = $this->url('mvitauction', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $auction->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
