<?php
$title = 'Edit auction';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('mvitauction/edit', array('id' => $this->id,)));
$form->prepare();

echo $this->form()->openTag($form)."\n";
echo $this->formHidden($form->get('id'))."\n";
echo $this->formHidden($form->get('user_id'))."\n";
#echo $this->formRow($form->get('created'))."\n";
echo $this->formRow($form->get('end_time'))."\n";
#echo $this->formRow($form->get('updated'))."\n";
echo $this->formRow($form->get('price'))."\n";
echo $this->formRow($form->get('buyout'))."\n";
echo $this->formRow($form->get('header'))."\n";
echo $this->formRow($form->get('body'))."\n";
#echo $this->formRow($form->get('protection'))."\n";
echo $this->formSubmit($form->get('submit'))."\n";
echo $this->form()->closeTag()."\n";
