<?php if(count($flashMessages)) { ?>
<ul>
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php
}
$title = $auction->header;
$this->headTitle($this->escapeHtml($title));
?>
<div class="row">
  <div class="span10">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php echo $this->escapeHtml($auction->body);?>
  </div>
  <div class="span2">
    <dl>
<?php if ($this->zfcUserIdentity()) { ?>
<?php if ($this->zfcUserIdentity()->getId() == $auction->user_id) { ?>
      <dt>Owner data:</dt>
      <dd><a href="<?php echo $this->url('mvitauction/edit', array('slug' => $auction->slug));?>">Edit auction</a><br/>Views: <?php echo $this->escapeHtml($auction->views); ?></dd>
<?php } } ?>
      <dt>End time:</dt>
      <dd><?php echo date("Y-m-d H:i", $this->escapeHtml($auction->end_time));?></dd>
      <dt>Start price:</dt>
      <dd><?php echo $this->escapeHtml($currency->before.$this->numberFormat($auction->price, NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, \Locale::getDefault(),2).$currency->after);?></dd>
<?php if ($auction->buyout > 0) { ?>
      <dt>Buyout price:</dt>
      <dd><?php echo $this->escapeHtml($currency->before.$this->numberFormat($auction->buyout, NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, \Locale::getDefault(),2).$currency->after);?></dd>
<?php } ?>
<?php if ($auction->bid_count) { ?>
      <dt>Current bid:</dt>
      <dd><?php echo $this->escapeHtml($currency->before.$this->numberFormat($bids[0]->bid, NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, \Locale::getDefault(),2).$currency->after);?></dd>
<?php } ?>
<?php if ($this->zfcUserIdentity()) { ?>
      <dt>Make your bid</dt>
      <dd>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('mvitauction/bid', array('action' => 'bid', 'slug' => $auction->slug,)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('bid'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
      </dd>
<?php } ?>
<?php if ($auction->bid_count) { ?>
      <dt>Bid history:</dt>
      <dd>
        <ul>
<?php foreach($bids as $bid) : ?>
          <li><?php echo $this->escapeHtml($currency->before.$this->numberFormat($bid->bid, NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, \Locale::getDefault(),2).$currency->after); ?> - <?php echo $bid->username; ?></li>
<?php endforeach; ?>
        </ul>
      </dd>
<?php } ?>
    </dl>
  </div>
</div>