<?php if(count($flashMessages)) { ?>
<ul>
    <?php foreach ($flashMessages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php
}
$title = $auction->header;
$this->headTitle($this->escapeHtml($title));
?>
<div class="row">
  <div class="span10">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php echo $this->escapeHtml($auction->body);?>
  </div>
  <div class="span2">
    <dl>
      <dt>End time:</dt>
      <dd><?php echo date("Y-m-d H:i", $this->escapeHtml($auction->end_time));?></dd>
      <dt>Start price:</dt>
      <dd><?php echo $this->escapeHtml($currency->before).$this->escapeHtml($auction->price).$this->escapeHtml($currency->after);?></dd>
<?php if ($auction->buyout) { ?>
      <dt>Buyout price:</dt>
      <dd><?php echo $this->escapeHtml($currency->before).$this->escapeHtml($auction->buyout).$this->escapeHtml($currency->after);?></dd>
<?php } ?>
<?php if (count($bids) > 0) { ?>
      <dt>Current bid:</dt>
      <dd><?php echo $this->escapeHtml($currency->before).$bids->current()->bid.$this->escapeHtml($currency->after);?></dd>
<?php } ?>
      <dt>Make your bid</dt>
      <dd>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('mvitauction/bid', array('action' => 'bid', 'slug' => $auction->slug,)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('bid'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
      </dd>
<?php if ($auction->bid_history) { ?>
      <dt>Bid history:</dt>
      <dd>
        <ul>
<?php foreach($bids as $bid) : ?>
          <li><?php echo $bid->bid; ?> - <?php echo $bid->user; ?></li>
<?php endforeach; ?>
        </ul>
      </dd>
<?php } ?>
    </dl>
  </div>
</div>
